version: "3"

services:
  mariadb:
    image: mariadb:10.9
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: jumpwire_test
      MYSQL_ROOT_PASSWORD: root
    command:
      - --ssl-ca=/etc/ssl/certs/local/minica.pem
      - --ssl-cert=/etc/ssl/certs/local/localhost.crt
      - --ssl-key=/etc/ssl/certs/local/localhost.key
    volumes:
      - ./../cert:/etc/ssl/certs/local
